version: "3"
services: 
    node:
        build: .
        container_name: node
        volumes: 
            - ./src:/app/src
            - ./shell:/app/shell
        command: bash -c "/app/shell/start.sh start"
        tty: true
